spring:
  profiles:
    active:
      on-profile: "prod"

build:
  version: "2.0"


accounts:
  message: "Hello from accounts production service"
  contactDetails:
    name: "accounts_prod"
    email: "accounts_prod@localhost"
  onCallSupport:
    - 1234447891
    - 9254441471

