spring:
  profiles:
    active:
      on-profile: "qa"

build:
  version: "2.0"


cards:
  message: "Hello from cards service"
  contactDetails:
    name: "cards_qa"
    email: "cards_qa@localhost"
  onCallSupport:
    -1234447891
    -9254441471

