spring:
  profiles:
    active:
      on-profile: "prod"

build:
  version: "2.0"


loans:
  message: "Hello from loans service"
  contactDetails:
    name: "loans_prod"
    email: "loans_prod@localhost"
  onCallSupport:
    -1234447891
    -9254441471

